modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="https://github.com/RainbowVille/minegasm/issues"
[[mods]]
modId="minegasm"
version="0.1.1"
displayName="MineGasm"
updateJSONURL="https://minegasm.therainbowville.com/updates.json"
displayURL="https://minegasm.therainbowville.com/"
logoFile="minegasm.png"
credits="Lone_Destroyer <3"
authors="RSwoop"
description='''
  Just a simple mod to bring some gasm into Minecraft. ;)
'''
[[dependencies.minegasm]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.minegasm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
