modLoader="javafml"
loaderVersion="[35,)"
license="Creative Commons Attribution Share Alike 4.0"
issueTrackerURL="https://github.com/RainbowVille/minegasm/issues"
[[mods]]
modId="minegasm"
version="0.2.0"
displayName="Minegasm"
updateJSONURL="https://minegasm.therainbowville.com/updates.json"
displayURL="https://minegasm.therainbowville.com/"
logoFile="minegasm.png"
authors="RSwoop"
description='''
  Just a simple mod to bring some gasm into Minecraft. ;)
'''
[[dependencies.minegasm]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.minegasm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
