# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle Build

on:
  push:
    branches: [ main ]
    paths:
      - '1.16/**'
  pull_request:
    branches: [ main ]
    paths:
      - '1.16/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x 1.16/gradlew        
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.0-beta.4
      with:
        build-root-directory: 1.16
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: build/libs
